// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Merchant struct {
	ID   string  `json:"id"`
	Name string  `json:"name"`
	URL  *string `json:"url"`
}

type MerchantInput struct {
	ID   *string `json:"id"`
	Name *string `json:"name"`
}

type NewMerchant struct {
	Name string  `json:"name"`
	URL  *string `json:"url"`
}
